### ISSUE TITLE
Consider upgrading to `@digitalbazaar/ed25519-signature-2020@5`

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-service-agent#17]
https://github.com/digitalbazaar/ed25519-signature-2020/blob/main/CHANGELOG.md#500---2022-08-23

Use jsonld-signatures@11 to get better safe mode protections when canonizing.

**Comment by dlongley** [comment]
Yes, this should be upgraded.

**Comment by mattcollier** [comment]
Landed in v8.
