### ISSUE TITLE
Intermittent failure in the `rotates an ephemeral agent` test

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-service-agent#19]
This test was run on commit bdefa614863972135abced98b58b563ca4315ab8

https://github.com/digitalbazaar/bedrock-service-agent/actions/runs/6200241589/job/16834522128#step:6:64

So far, the failure has only been seen once in this github action.

**Comment by mattcollier** [comment]
Happened again: https://github.com/digitalbazaar/bedrock-service-agent/actions/runs/6200241589/job/16835961725

**Comment by dlongley** [comment]
We probably need to tweak the timing and see if that's good enough -- otherwise we'd need some more fancy hooks to trigger rotation manually during testing ... which means we might not actually be testing real behavior, which would be problematic.
